default:
  image: docker:27.3.1
  services:
    - docker:dind

  before_script:
    - until docker info; do sleep 1; done

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

stages:
 - test
 - release
 - deploy 

test:
  stage: test
  script:
  - ./test/test.sh

release:
  stage: release
  variables:
    IMAGE_TAG: ${CI_REGISTRY_IMAGE}/image:$CI_COMMIT_REF_SLUG
  script:
    - echo $IMAGE_TAG
    - cd src
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker compose build
    - docker image tag dns_updater:latest $IMAGE_TAG
    - docker push $IMAGE_TAG

deploy:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
  - kubectl apply -f k8s/deployment.yaml
