default:
  image: docker:24.0.5
  before_script:
    - docker info


biuld:
  stage: compose
  script:
  - docker compose build


test:
  stage: test
  script:
  - ./test.sh

release:
  stage: release
  script:
  - docker image tag dns_updater:latest gitlab-registry/dns_updater:latest
  - docker push gitlab-registry/dns_updater:latest 

deploy:
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
  - kubectl get pods
