default:
  image: docker:27.3.1
  services:
    - docker:dind

  before_script:
    - docker info

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"


compose:
  stage: build
  script:
  - cd src
  - docker compose build


test:
  stage: test
  script:
  - ./test/test.sh

release:
  stage: deploy
  script:
  - cd src
  - docker image tag dns_updater:latest gitlab-registry/dns_updater:latest
  - docker push gitlab-registry/dns_updater:latest 

deploy:
  stage: deploy
  needs:
    - release
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
  - kubectl get pods
