default:
  image: docker:24.0.5
  before_script:
    - docker info


compose:
  stage: build
  script:
  - docker compose build


test:
  stage: test
  script:
  - ./test.sh

release:
  stage: deploy
  script:
  - docker image tag dns_updater:latest gitlab-registry/dns_updater:latest
  - docker push gitlab-registry/dns_updater:latest 

deploy:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
  - kubectl get pods
