apiVersion: v1
kind: Namespace
metadata: 
  name: infra
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: dns-updater
  namespace: infra
  labels:
    app: dns-updater
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dns-updater
  template: 
    metadata:
      labels:
        app: dns-updater
    spec: 
      imagePullSecrets: 
        - name: regcred
      containers:
      - name: dns-updater
        image: distribution.organiccode.net/dns_updater:latest
        env: 
        - name: GO_DADDY_API_KEY
          valueFrom:
            secretKeyRef:
              name: godaddy-api-secret
              key: apiToken
              optional: false
            